### ISSUE TITLE
Error in ./CreateAccountPage class CreateAccountPage - caused by: self.context.createAccount is not a function

### ISSUE THREAD

**Issue by bellarmin** [luisjmrtnz/ionic-social-network#1]
Hi Luis,

I am getting below error while trying to register a new user. Could you please help me to resolve the issue. I am totally new to Ionic 2 and web development.

**Error in ./CreateAccountPage class CreateAccountPage - caused by: self.context.createAccount is not a function**

I know little bit of HTML/CSS and basics on javascripts.

Please guide me how to start for creating a good APP especially on mobiles.
I am interested in creating a social network based app and i am just look in your code.

**Comment by luisjmrtnz** [comment]
Thank you for stopping by at my code! 
You receive that error because I haven't create that function yet. Right now I'm working on it. Keep watching I think in less than an hour I will submitting the new function

**Comment by luisjmrtnz** [comment]
It's done, I already resolve this issue. @bellarmin

**Comment by bellarmin** [comment]
Thanks Luis. Please let me know the best way to start with app development. I have some thought like integrating the Social network and eCommerce together.
